name: JobLink for Git
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
env:
  jr_process_name: git_demo_patrick
  jr_process_version: 1
jobs:
  build:
    if: ${{ !contains(github.event.head_commit.message, 'Initial Commit from JobRouter Process') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Run a deploy script
        run: |
          php ./build/push-to-jobrouter.php "${{ env.jr_process_name }}" "${{ env.jr_process_version }}" "${{ secrets.JR_URL }}" "${{ secrets.JR_USER }}" "${{ secrets.JR_PASSWORD }}"
      - name: cURL AxiosJS
        uses: indiesdev/curl@v1.1
